<?php
use PHPUnit\Framework\TestCase;
use NumbersTranslator\Translator;

class TranslatorTest extends TestCase
{

    public function testInvalidArgumentWrongLength()
    {
        $this->expectException(InvalidArgumentException::class);

        Translator::make(11111111111111111);
    }

    /**
     * @dataProvider additionProvider
     */
    public function testReturnsTheСorrectString($expected, $actual)
    {
        $this->assertEquals(
            $expected,
            $actual
        );
    }

    public function additionProvider()
    {
        return [
            ['one', Translator::make(01)],
            ['one', Translator::make(001)],
            ['one', Translator::make(1)],
            ['five', Translator::make(5)],
            ['nine', Translator::make(9)],
            ['ten', Translator::make(10)],
            ['fourteen', Translator::make(14)],
            ['nineteen', Translator::make(19)],
            ['twenty', Translator::make(20)],
            ['twenty-five', Translator::make(25)],
            ['twenty-nine', Translator::make(29)],
            ['sixty-eight', Translator::make(68)],
            ['ninety-nine', Translator::make(99)],
            ['one hundred', Translator::make(100)],
            ['one hundred and five', Translator::make(105)],
            ['one hundred and ten', Translator::make(110)],
            ['one hundred and seventeen', Translator::make(117)],
            ['one hundred and forty', Translator::make(140)],
            ['one hundred and sixty-three', Translator::make(163)],
            ['one thousand', Translator::make(1000)],
            ['one thousand and five', Translator::make(1005)],
            ['one thousand and eleven', Translator::make(1011)],
            ['one thousand and twenty-three', Translator::make(1023)],
            ['one thousand four hundred and fifty-five', Translator::make(1455)],
            ['ten thousand', Translator::make(10000)],
            ['ten thousand and seven', Translator::make(10007)],
            ['ten thousand and seventeen', Translator::make(10017)],
            ['ten thousand and seventy-seven', Translator::make(10077)],
            ['ten thousand one hundred and seven', Translator::make(10107)],
            ['ten thousand one hundred and seventy-seven', Translator::make(10177)],
            ['fourteen thousand one hundred and seventy-seven', Translator::make(14177)],
            ['one hundred thousand', Translator::make(100000)],
            ['one hundred thousand and two', Translator::make(100002)],
            ['one hundred thousand and sixteen', Translator::make(100016)],
            ['one hundred thousand one hundred and six', Translator::make(100106)],
            ['one hundred and seven thousand one hundred and six', Translator::make(107106)],
            ['one hundred and eighty-seven thousand one hundred and six', Translator::make(187106)],
            ['one hundred and eighty-seven thousand one hundred and sixteen', Translator::make(187116)],
            ['one hundred and eighty-seven thousand one hundred and fifty-six', Translator::make(187156)],
            ['one hundred and sixty-three thousand and four', Translator::make(163004)],
            ['two million', Translator::make(2000000)],
            ['two million and one', Translator::make(2000001)],
            ['two million and thirteen', Translator::make(2000013)],
            ['two million and forty-eight', Translator::make(2000048)],
            ['two million two hundred and forty-eight', Translator::make(2000248)],
            ['two million and one thousand and forty-eight', Translator::make(2001048)],
            ['two million and fifteen thousand and forty-eight', Translator::make(2015048)],
            ['two million and eighty-five thousand and forty-eight', Translator::make(2085048)],
            ['two million seven hundred and five thousand and forty-eight', Translator::make(2705048)],
            ['two million one hundred and twenty-five thousand and forty-eight', Translator::make(2125048)],
            ['two million five hundred and fifty-five thousand and forty-eight', Translator::make(2555048)],
            ['twenty million', Translator::make(20000000)],
            ['twenty million and one', Translator::make(20000001)],
            ['twenty million and thirteen', Translator::make(20000013)],
            ['twenty million and forty-eight', Translator::make(20000048)],
            ['twenty million two hundred and forty-eight', Translator::make(20000248)],
            ['twenty million and ten thousand and forty-eight', Translator::make(20010048)],
            ['twenty million eight hundred and fifty thousand and forty-eight', Translator::make(20850048)],
            ['twenty-seven million and fifteen thousand and forty-eight', Translator::make(27015048)],
            ['twenty-one million two hundred and fifteen thousand and forty-eight', Translator::make(21215048)],
            ['twenty-one million five hundred and fifty-five thousand and forty-eight', Translator::make(21555048)],
            ['two hundred million', Translator::make(200000000)],
            ['two hundred million and one', Translator::make(200000001)],
            ['two hundred million and thirteen', Translator::make(200000013)],
            ['two hundred million and forty-eight', Translator::make(200000048)],
            ['two hundred million two hundred and forty-eight', Translator::make(200000248)],
            ['two hundred million one hundred thousand and forty-eight', Translator::make(200100048)],
            ['two hundred and eight million five hundred thousand and forty-eight', Translator::make(208500048)],
            ['two hundred and seventy million and fifteen thousand and forty-eight', Translator::make(270015048)],
            ['two hundred and ten million two hundred and fifteen thousand and forty-eight', Translator::make(210215048)],
            ['two hundred and fifteen million and fifty-five thousand and forty-eight', Translator::make(215055048)],
            ['nine billion', Translator::make(9000000000)],
            ['eight billion and one', Translator::make(8000000001)],
            ['seven billion and thirteen', Translator::make(7000000013)],
            ['six billion and forty-eight', Translator::make(6000000048)],
            ['five billion two hundred and forty-eight', Translator::make(5000000248)],
            ['four billion and one million and forty-eight', Translator::make(4001000048)],
            ['three billion and eight million five hundred thousand and forty-eight', Translator::make(3008500048)],
            ['two billion seven hundred million and fifteen thousand and forty-eight', Translator::make(2700015048)],
            ['two billion one hundred and two million and fifteen thousand and forty-eight', Translator::make(2102015048)],
            ['four billion one hundred and fifty million five hundred and five thousand and forty-eight', Translator::make(4150505048)],
            ['two billion and one million five hundred thousand and forty-eight', Translator::make(2001500048)],
            ['forty-five billion one hundred and sixty-eight million and fifteen thousand and sixty', Translator::make(45168015060)],
            ['five hundred and seventy-six billion and sixty-four million eight hundred and twenty thousand seven hundred and sixteen', Translator::make(576064820716)],
            ['four trillion seven hundred and twenty-one billion five hundred and six million and ninety-eight thousand five hundred and twelve', Translator::make(4721506098512)],
            ['ninety-seven trillion five hundred and forty-two billion and fifty million six hundred and forty thousand seven hundred', Translator::make(97542050640700)],
            ['five hundred and seventy trillion one hundred and sixty billion five hundred and seventy million four hundred and eighty-four thousand and twenty-six', Translator::make(570160570484026)],
            ['eight quadrillion seven hundred and fifty-four trillion six hundred and nineteen billion two hundred and four million five hundred and five thousand seven hundred and six', Translator::make(8754619204505706)],

            ['one', Translator::make(1, 'usa')],
            ['five', Translator::make(5, 'usa')],
            ['nine', Translator::make(9, 'usa')],
            ['ten', Translator::make(10, 'usa')],
            ['fourteen', Translator::make(14, 'usa')],
            ['nineteen', Translator::make(19, 'usa')],
            ['twenty', Translator::make(20, 'usa')],
            ['twenty-five', Translator::make(25, 'usa')],
            ['twenty-nine', Translator::make(29, 'usa')],
            ['sixty-eight', Translator::make(68, 'usa')],
            ['ninety-nine', Translator::make(99, 'usa')],
            ['one hundred', Translator::make(100, 'usa')],
            ['one hundred five', Translator::make(105, 'usa')],
            ['one hundred ten', Translator::make(110, 'usa')],
            ['one hundred seventeen', Translator::make(117, 'usa')],
            ['one hundred forty', Translator::make(140, 'usa')],
            ['one hundred sixty-three', Translator::make(163, 'usa')],
            ['one thousand', Translator::make(1000, 'usa')],
            ['one thousand five', Translator::make(1005, 'usa')],
            ['one thousand eleven', Translator::make(1011, 'usa')],
            ['one thousand twenty-three', Translator::make(1023, 'usa')],
            ['one thousand four hundred fifty-five', Translator::make(1455, 'usa')],
            ['ten thousand', Translator::make(10000, 'usa')],
            ['ten thousand seven', Translator::make(10007, 'usa')],
            ['ten thousand seventeen', Translator::make(10017, 'usa')],
            ['ten thousand seventy-seven', Translator::make(10077, 'usa')],
            ['ten thousand one hundred seven', Translator::make(10107, 'usa')],
            ['ten thousand one hundred seventy-seven', Translator::make(10177, 'usa')],
            ['fourteen thousand one hundred seventy-seven', Translator::make(14177, 'usa')],
            ['one hundred thousand', Translator::make(100000, 'usa')],
            ['one hundred thousand two', Translator::make(100002, 'usa')],
            ['one hundred thousand sixteen', Translator::make(100016, 'usa')],
            ['one hundred thousand one hundred six', Translator::make(100106, 'usa')],
            ['one hundred seven thousand one hundred six', Translator::make(107106, 'usa')],
            ['one hundred eighty-seven thousand one hundred six', Translator::make(187106, 'usa')],
            ['one hundred eighty-seven thousand one hundred sixteen', Translator::make(187116, 'usa')],
            ['one hundred eighty-seven thousand one hundred fifty-six', Translator::make(187156, 'usa')],
            ['one hundred sixty-three thousand four', Translator::make(163004, 'usa')],
            ['two million', Translator::make(2000000, 'usa')],
            ['two million one', Translator::make(2000001, 'usa')],
            ['two million thirteen', Translator::make(2000013, 'usa')],
            ['two million forty-eight', Translator::make(2000048, 'usa')],
            ['two million two hundred forty-eight', Translator::make(2000248, 'usa')],
            ['two million one thousand forty-eight', Translator::make(2001048, 'usa')],
            ['two million fifteen thousand forty-eight', Translator::make(2015048, 'usa')],
            ['two million eighty-five thousand forty-eight', Translator::make(2085048, 'usa')],
            ['two million seven hundred five thousand forty-eight', Translator::make(2705048, 'usa')],
            ['two million one hundred twenty-five thousand forty-eight', Translator::make(2125048, 'usa')],
            ['two million five hundred fifty-five thousand forty-eight', Translator::make(2555048, 'usa')],
            ['twenty million', Translator::make(20000000, 'usa')],
            ['twenty million one', Translator::make(20000001, 'usa')],
            ['twenty million thirteen', Translator::make(20000013, 'usa')],
            ['twenty million forty-eight', Translator::make(20000048, 'usa')],
            ['twenty million two hundred forty-eight', Translator::make(20000248, 'usa')],
            ['twenty million ten thousand forty-eight', Translator::make(20010048, 'usa')],
            ['twenty million eight hundred fifty thousand forty-eight', Translator::make(20850048, 'usa')],
            ['twenty-seven million fifteen thousand forty-eight', Translator::make(27015048, 'usa')],
            ['twenty-one million two hundred fifteen thousand forty-eight', Translator::make(21215048, 'usa')],
            ['twenty-one million five hundred fifty-five thousand forty-eight', Translator::make(21555048, 'usa')],
            ['two hundred million', Translator::make(200000000, 'usa')],
            ['two hundred million one', Translator::make(200000001, 'usa')],
            ['two hundred million thirteen', Translator::make(200000013, 'usa')],
            ['two hundred million forty-eight', Translator::make(200000048, 'usa')],
            ['two hundred million two hundred forty-eight', Translator::make(200000248, 'usa')],
            ['two hundred million one hundred thousand forty-eight', Translator::make(200100048, 'usa')],
            ['two hundred eight million five hundred thousand forty-eight', Translator::make(208500048, 'usa')],
            ['two hundred seventy million fifteen thousand forty-eight', Translator::make(270015048, 'usa')],
            ['two hundred ten million two hundred fifteen thousand forty-eight', Translator::make(210215048, 'usa')],
            ['two hundred fifteen million fifty-five thousand forty-eight', Translator::make(215055048, 'usa')],
            ['nine billion', Translator::make(9000000000, 'usa')],
            ['eight billion one', Translator::make(8000000001, 'usa')],
            ['seven billion thirteen', Translator::make(7000000013, 'usa')],
            ['six billion forty-eight', Translator::make(6000000048, 'usa')],
            ['five billion two hundred forty-eight', Translator::make(5000000248, 'usa')],
            ['four billion one million forty-eight', Translator::make(4001000048, 'usa')],
            ['three billion eight million five hundred thousand forty-eight', Translator::make(3008500048, 'usa')],
            ['two billion seven hundred million fifteen thousand forty-eight', Translator::make(2700015048, 'usa')],
            ['two billion one hundred two million fifteen thousand forty-eight', Translator::make(2102015048, 'usa')],
            ['four billion one hundred fifty million five hundred five thousand forty-eight', Translator::make(4150505048, 'usa')],
            ['two billion one million five hundred thousand forty-eight', Translator::make(2001500048, 'usa')],
            ['forty-five billion one hundred sixty-eight million fifteen thousand sixty', Translator::make(45168015060, 'usa')],
            ['five hundred seventy-six billion sixty-four million eight hundred twenty thousand seven hundred sixteen', Translator::make(576064820716, 'usa')],
            ['four trillion seven hundred twenty-one billion five hundred six million ninety-eight thousand five hundred twelve', Translator::make(4721506098512, 'usa')],
            ['ninety-seven trillion five hundred forty-two billion fifty million six hundred forty thousand seven hundred', Translator::make(97542050640700, 'usa')],
            ['five hundred seventy trillion one hundred sixty billion five hundred seventy million four hundred eighty-four thousand twenty-six', Translator::make(570160570484026, 'usa')],
            ['eight quadrillion seven hundred fifty-four trillion six hundred nineteen billion two hundred four million five hundred five thousand seven hundred six', Translator::make(8754619204505706, 'usa')]
        ];
    }
}